### PR TITLE
Make sure default container captures all scripts

### PR DESCRIPTION
**Pull request by Helen-Mobify**
Descript is not pulling in all the scripts into the default container. Descript only pulls in the following:
* script that have `x-src`
* script that have `type="mobify-script"`

It doesn't account for any script tags that isn't transformed properly by our capturejs. For example,

```<script language="javascript">```

Status: **Ready to Merge**

Reviewers: @donnielrt @fractaltheory 

## Changes
- Make sure the default container is capturing all scripts

## TODO
- [ ] Eng + 1
- [x] Test all passed
- [x] Version incremented

### CODE REVIEW

**Comment by ericmuyser** [comment]
Seems reasonable. What are your thoughts on why capturejs didn't catch that script though? Because it didn't have a type attribute? Seems strange. I would expect it to have caught it and added `type="mobify-script"`. Thoughts?

**Comment by Helen-Mobify** [comment]
@ericmuyser Good question. I have no idea either. @jansepar Do you know why capturejs only transform script tag that have `src` and `type` attribute?

**Comment by jansepar** [comment]
@Helen-Mobify I would actually consider that a bug - we should be making sure that all script elements are escaped. The reason we escape inline scripts is because if we don't, they would execute when creating the captured doc (although with the way we're creating the captured doc now, I'm not sure if that's still the case).

**Comment by fractaltheory** [comment]
@Helen-Mobify Just to recap our offline discussion - I'm not seeing this behavior on Deluxe (i.e. Descript appears to be picking things up properly for me). Take another look and if the issue is resolved on Deluxe, we can close this PR for now.

**Comment by Helen-Mobify** [comment]
Wow... ya. My chrome was acting super weird. Closing ticket.

**Pull request closed without merging**
